name: open_file_plugin
description: "The \"Open File plugin\" streamlines file handling by seamlessly managing various file types within the application. Users can effortlessly view files in their default software, enhancing accessibility and simplifying workflows."
version: 0.0.3
homepage: https://github.com/whizpool/Open_File_Plugin.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.whizpool.openfile
        pluginClass: OpenfilePlugin
      ios:
        pluginClass: OpenfilePlugin
      linux:
        pluginClass: OpenfilePlugin
      macos:
        pluginClass: OpenfilePlugin
      windows:
        pluginClass: OpenfilePluginCApi
      web:
        pluginClass: OpenfileWeb
        fileName: openfile_web.dart